benchmark_type: chat
dataset_names: [sharegpt]
max_input_tokens: 2048
target_output_tokens: 512
num_samples: 200
min_success_rate: 1.0
prefix_cache: false
precision: bfloat16
hf_dataset: json
hf_data_files: https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json
dataset_split: train
