batch_sizes: [2, 4, 8, 16, 32, 64, 128]
benchmark_types:
  prefill: [batched_prefill]
  chat: [sharegpt]
  reasoning: [mmlu_pro]
  agentic: [mini_swe_agent]
port: 30000
estimator_mode: component-wise

# SGLang options:
#   - --disable-custom-all-reduce
#   - --disable-radix-cache
#   - --context-length: 40960
#   - --chunked-prefill-size: 16384
#   - --max-prefill-tokens: 40960
#   - --mem-fraction-static: 0.90
#   - --dtype: bfloat16
#   - --served-model-name: qwen3_30b
#   - --expert-distribution-recorder-mode: stat
#   - --enable-return-routed-experts
#   - --enable-expert-distribution-metrics
sglang_server_flags:
  - --disable-custom-all-reduce
  - --disable-radix-cache
  - --expert-distribution-recorder-mode: stat
  - --enable-return-routed-experts
  - --enable-expert-distribution-metrics

models:
  - id: Qwen/Qwen3-30B-A3B
    slug: qwen3_30b
    tp: 4
    sglang_server_flags:
      - --served-model-name: qwen3_30b
      - --dtype: bfloat16
      - --context-length: 40960
      - --chunked-prefill-size: 16384
      - --mem-fraction-static: 0.90
